In [1]:
# 1. Convert a Tuple t = (1,2,3,4,5) to list
t = (1,2,3,4,5)
print(t) 
print(type(t))

l = list(t)
print(l)
print(type(l))

(1, 2, 3, 4, 5)
<class 'tuple'>
[1, 2, 3, 4, 5]
<class 'list'>


In [2]:
# 2. WAP to join a list and a tuple and store results in List 

L = [1,3,5,7]
T = (8,6,4,2)
print("List " , L)
print("Tuple ", T)

#convert Tuple to list and store L list into new list 
L1 = list(T)
print("tuple to list ", L1)

# new list 
L_final = L + L1
print("Final list ", L_final)

List  [1, 3, 5, 7]
Tuple  (8, 6, 4, 2)
tuple to list  [8, 6, 4, 2]
Final list  [1, 3, 5, 7, 8, 6, 4, 2]


## 3. What is the difference between List and tuple 

##### a. Tuples and Lists both used to store collection of data
##### b. Both are heterogeneous - means they can store any kind of data
##### c. They both ordered - means the order we put the items are kept the same way.
##### d. They both are sequenced data types - so we can iterate over items containced in sequential order
##### e. Items in both can be accessed by an integer index operator 
##### f.  Tuples are immutable objects where as Lists are mutable. 
##### g. Tuples requires less memory when compare to Lists
##### f.  Tuples are more time efficient compared to List 
##### h. If we have data which is meant for not to change, then tuple option is good.

In [3]:
#4 . Print the list in reverse order
l = ['a','b','c','A','C']
print("list ", l)
# reverse the list
print("reverse list ", l[::-1])

list  ['a', 'b', 'c', 'A', 'C']
reverse list  ['C', 'A', 'c', 'b', 'a']


In [4]:
# 5. Print elements at Odd indexes from a list (Do not use loop)
l = [10,11,20,21,30,31,40,41]

print("elements in ODD indexes ", l[1::2])

elements in ODD indexes  [11, 21, 31, 41]


In [5]:
# 6. How many ways you can copy a list 
# there are 3 ways to copy a list 

# a. By slicing method  ==> both a and b are pointing to same memory location 
# e.g 
a = [1,2,4,5]
b = a[:]
print ("list a ==>", a)
print ("list b ==>", b)

# b. by using list() method 
# e.g.
print("  ")
a = 'hello'
b = list(a)
print ("string ==>", a)
print ("list b ==>", b)

# c. by using copy() method 
print("  ")
a = [1,2,4,5]
b = a.copy()
print ("list a ==>", a)
print ("list b ==>", b)

list a ==> [1, 2, 4, 5]
list b ==> [1, 2, 4, 5]
  
string ==> hello
list b ==> ['h', 'e', 'l', 'l', 'o']
  
list a ==> [1, 2, 4, 5]
list b ==> [1, 2, 4, 5]


In [6]:
# 7. predict output
n_list = ["Happy",[2,0,1,5]]
print(n_list[0][1])  # a
print(n_list[1][3])  # 5

a
5


In [7]:
# 8. predict output
odd = [2,4,6,8]
odd[0] = 1  
print(odd) 
odd[1:4] = [3,5,7]
print(odd) 

[1, 4, 6, 8]
[1, 3, 5, 7]


In [8]:
# 9. predict output
odd = [1,3,5]
odd.append([7,9])
print(odd) # append new elments as list to list
odd.extend([11,13])
print(odd) # extend the exiting list 

[1, 3, 5, [7, 9]]
[1, 3, 5, [7, 9], 11, 13]


In [9]:
# 10 predict output 
x = 1,2,3; print(type(x))
x = (1); print(type(x))
x = 1; print(type(x))
x = 1,; print(type(x))

<class 'tuple'>
<class 'int'>
<class 'int'>
<class 'tuple'>


In [10]:
# 11 try to repesent a matrix with following data in python

# Option # 1
print(1,2,3); print(4,5,6);print(7,8,9)

# Option # 2
print(" ")
import numpy as np
m = np.matrix([[1,2,3], [4,5,6],[7,8,9]])
print('Matrix is:\n', m)

1 2 3
4 5 6
7 8 9
 
Matrix is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# 12. Predict output 
t = tuple('string')
print(t)
print(t[::-1]) # reverse 
print(t[::2][::-2]) # print letter at specified index 

('s', 't', 'r', 'i', 'n', 'g')
('g', 'n', 'i', 'r', 't', 's')
('n', 's')


In [12]:
# 13 predict output
t = tuple ([10,20,30,40,50,60])
print(60 in t)
print('60' in t)
print(t.count(10))
print(t.index(40))

True
False
1
3


In [13]:
# 14 WAP a program to input a string and print if it is palindrome or not 
# palindrome string
my_str = input("enter a string") 

my_str = my_str.lower()

rev_str = my_str[::-1] # reverse string 

if list(my_str) == list(rev_str): #string and rev string is equal or not
   print("The string is a palindrome.")
else:
   print("The string is not a palindrome.")

enter a stringstring
The string is not a palindrome.


In [14]:
# 15. Use the range method and create a tuple containing the following values: (20,15,10,5)
s = range(20,0,-5)
print(tuple(s))

(20, 15, 10, 5)


In [15]:
# 16. WAP to convert string to list of charecters 
a = 'hello'
b = list(a)
print ("string ==>", a)
print ("list b ==>", b)

string ==> hello
list b ==> ['h', 'e', 'l', 'l', 'o']


In [16]:
# 17. what is the return type of below.
print(type('1 2'.split() )) # list
print(type( [1,3,2].sort()))
print(type( 'abc'.upper()))
print(type( 1 in [1,2]))

<class 'list'>
<class 'NoneType'>
<class 'str'>
<class 'bool'>
